---
provider: Cloudflare
email: 'E-mail address'
login_token: 'API Token from https://dash.cloudflare.com/profile/api-tokens'
resolver: 1.1.1.1
ip_url: https://api.ipify.org/
ip_type: IPv4
interval: 300
domains:
  - domain_name: hoppner.se
    sub_domains:
      - cloud
      - pi-hole
      - home-assistant
