---
provider: Cloudflare
email: foo@example.com
login_token: abc123  # From https://dash.cloudflare.com/profile/api-tokens
resolver: 1.1.1.1
ip_url: https://api.ipify.org/
ip_type: IPv4
interval: 300
domains:
  - domain_name: hoppner.se
    sub_domains:
      - "@"  # Also update the root domain
      - cloud
      - pi-hole
      - home-assistant
