---
x-variables:
  time-zone: &time-zone Europe/Stockholm

services:
  godns:
    image: godns
    build:
      context: ./godns
      args:
        GODNS_VERSION: v2.8.4
        BASE_IMAGE_TAG: 1.18-alpine
    volumes:
      - ./godns/config:/config:ro
    restart: unless-stopped

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    volumes:
      - ./home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - pihole

  pihole:
    image: pihole/pihole:latest
    ports:
      # DNS ports
      - 53:53/tcp
      - 53:53/udp
      # Don't open HTTP here as that's reverse proxied by SWAG
    environment:
      FTLCONF_REPLY_ADDR4: "${LOCAL_IP?Run with compose_wrap.sh!}"
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      TZ: *time-zone
      WEBPASSWORD: "${PIHOLE_WEB_PASSWORD?Run with compose_wrap.sh!}"
      WEBTHEME: default-dark
    volumes:
      - ./pihole/config:/etc/pihole
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag:latest
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    environment:
      TZ: *time-zone
      URL: hoppner.se
      SUBDOMAINS: home-assistant,pihole,
      VALIDATION: http
      CERTPROVIDER: letsencrypt
      EMAIL: "${SWAG_EMAIL?Run with compose_wrap.sh!}"
      STAGING: 'false'
    volumes:
      - ./swag/config:/config
    restart: unless-stopped
    depends_on:
      - pihole

networks:
  default:
    ipam:
      config:
        # Give the default Docker network a predictable IP address range so we
        # can give Home Assistant an IP range of trusted proxies.
        - subnet: 172.10.0.0/24
