---
x-variables:
  time-zone: &time-zone Europe/Stockholm

services:
  godns:
    build:
      context: ./godns
      args:
        GODNS_VERSION: v2.9.3
        BASE_IMAGE_TAG: 1.20-alpine
    volumes:
      - ./godns/config:/config:ro
    restart: unless-stopped
    depends_on:
      - pi-hole

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    privileged: true
    volumes:
      - ./home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      - pi-hole
      - swag

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    environment:
      TZ: *time-zone
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/data:/data
    restart: unless-stopped
    depends_on:
      - pi-hole
      - swag

  pi-hole:
    image: pihole/pihole:latest
    ports:
      # DNS ports
      - 53:53/tcp
      - 53:53/udp
      # Don't open HTTP here as that's reverse proxied by SWAG
    environment:
      # Setting DNSMASQ_LISTENING is recommended by the readme on Docker Hub
      DNSMASQ_LISTENING: all
      FTLCONF_REPLY_ADDR4: "${LOCAL_IP?Create a .env file! See env.template}"
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      TZ: *time-zone
      WEBPASSWORD: "${PIHOLE_WEB_PASSWORD?Create a .env file! See env.template}"
      WEBTHEME: default-dark
    volumes:
      - ./pi-hole/config:/etc/pihole
      - ./pi-hole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    depends_on:
      - swag

  swag:
    image: lscr.io/linuxserver/swag:latest
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    environment:
      TZ: *time-zone
      URL: hoppner.se
      SUBDOMAINS: nextcloud,home-assistant,pi-hole,
      VALIDATION: http
      CERTPROVIDER: letsencrypt
      EMAIL: "${SWAG_EMAIL?Create a .env file! See env.template}"
      STAGING: 'false'
    volumes:
      - ./swag/config:/config
    restart: unless-stopped
    depends_on:
      # SWAG dosen't start up properly until the website container exists. Not
      # sure why. Maybe because that's the only website that's not a subdomain?
      - website

  website:
    build:
      context: ./website
      args:
        RUST_VERSION: 1.67.1
        ALPINE_VERSION: 3.17
        RUST_PROFILE: ${RUST_PROFILE:-release}
    environment:
      RUST_LOG: "${RUST_LOG:-info,tower_http::trace=debug}"
    volumes:
      - ./website/templates:/templates:ro
      - ./website/static:/static:ro
    restart: unless-stopped

networks:
  default:
    ipam:
      config:
        # Give the default Docker network a predictable IP address range so we
        # can give Home Assistant an IP range of trusted proxies.
        - subnet: 172.10.0.0/24
