---
x-variables:
  time-zone: &time-zone Europe/Stockholm
  defaults: &defaults
    restart: unless-stopped
    extra_hosts:
      - home-assistant:${LOCAL_IP?Create a .env file! See env.template}
  lsio_envs: &lsio-envs
    PGID: "${GID?Create a .env file! See env.template}"
    PUID: "${UID?Create a .env file! See env.template}"
    TZ: *time-zone

services:
  godns:
    build:
      context: ./godns
      args:
        GODNS_VERSION: v2.9.4
        BASE_IMAGE_TAG: 1.20-alpine
    volumes:
      - ./godns/config:/config:ro
    depends_on:
      - pi-hole
    <<: *defaults

  home-assistant:
    image: lscr.io/linuxserver/homeassistant:latest
    environment:
      <<: *lsio-envs
      DOCKER_MODS: linuxserver/mods:homeassistant-hacs
    volumes:
      - ./home-assistant/config:/config
    network_mode: host
    depends_on:
      - pi-hole
      - swag
    <<: *defaults

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    environment: *lsio-envs
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/data:/data
    depends_on:
      - pi-hole
      - swag
    <<: *defaults

  pi-hole:
    image: pihole/pihole:latest
    ports:
      # DNS ports
      - 53:53/tcp
      - 53:53/udp
      # Don't open HTTP here as that's reverse proxied by SWAG
    environment:
      # Setting DNSMASQ_LISTENING is recommended by the readme on Docker Hub
      DNSMASQ_LISTENING: all
      FTLCONF_REPLY_ADDR4: "${LOCAL_IP?Create a .env file! See env.template}"
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      # The UID/GID variables are marked as experimental, so this might break in
      # the future.
      PIHOLE_GID: "${GID?Create a .env file! See env.template}"
      PIHOLE_UID: "${UID?Create a .env file! See env.template}"
      TZ: *time-zone
      WEBPASSWORD: "${PIHOLE_WEB_PASSWORD?Create a .env file! See env.template}"
      WEBTHEME: default-dark
    volumes:
      - ./pi-hole/config:/etc/pihole
      - ./pi-hole/dnsmasq.d:/etc/dnsmasq.d
    depends_on:
      - swag
    <<: *defaults

  swag:
    image: lscr.io/linuxserver/swag:latest
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    environment:
      <<: *lsio-envs
      URL: hoppner.se
      SUBDOMAINS: nextcloud,home-assistant,pi-hole,
      VALIDATION: http
      CERTPROVIDER: letsencrypt
      EMAIL: "${SWAG_EMAIL?Create a .env file! See env.template}"
      STAGING: 'false'
    volumes:
      - ./swag/config:/config
    depends_on:
      # SWAG dosen't start up properly until the website container exists. Not
      # sure why. Maybe because that's the only website that's not a subdomain?
      - website
    <<: *defaults

  website:
    build:
      context: ./website
      args:
        RUST_VERSION: 1.67.1
        ALPINE_VERSION: 3.17
        RUST_PROFILE: ${RUST_PROFILE:-release}
    environment:
      RUST_LOG: "${RUST_LOG:-info,tower_http::trace=debug}"
    volumes:
      - ./website/templates:/templates:ro
      - ./website/static:/static:ro
    <<: *defaults

networks:
  default:
    ipam:
      config:
        # Give the default Docker network a predictable IP address range so we
        # can give Home Assistant an IP range of trusted proxies.
        - subnet: 172.10.0.0/24
