---
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

device_tracker:
  - platform: linksys_smart
    host: 192.168.1.1

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.10.0.0/24   # Docker network address range
    - 192.168.1.0/24  # Local network
